export interface Country {
  iso: string;
  name: string;
  dial: string;
  flag: string;
}

export const COUNTRIES: Country[] = [
  { iso: "US", name: "United States", dial: "1", flag: "🇺🇸" },
  { iso: "CA", name: "Canada", dial: "1", flag: "🇨🇦" },
  { iso: "GB", name: "United Kingdom", dial: "44", flag: "🇬🇧" },
  { iso: "IN", name: "India", dial: "91", flag: "🇮🇳" },
  { iso: "AU", name: "Australia", dial: "61", flag: "🇦🇺" },
  { iso: "DE", name: "Germany", dial: "49", flag: "🇩🇪" },
  { iso: "FR", name: "France", dial: "33", flag: "🇫🇷" },
  { iso: "JP", name: "Japan", dial: "81", flag: "🇯🇵" },
  { iso: "CN", name: "China", dial: "86", flag: "🇨🇳" },
  { iso: "BR", name: "Brazil", dial: "55", flag: "🇧🇷" },
  { iso: "MX", name: "Mexico", dial: "52", flag: "🇲🇽" },
  { iso: "ES", name: "Spain", dial: "34", flag: "🇪🇸" },
  { iso: "IT", name: "Italy", dial: "39", flag: "🇮🇹" },
  { iso: "NL", name: "Netherlands", dial: "31", flag: "🇳🇱" },
  { iso: "SE", name: "Sweden", dial: "46", flag: "🇸🇪" },
  { iso: "NO", name: "Norway", dial: "47", flag: "🇳🇴" },
  { iso: "DK", name: "Denmark", dial: "45", flag: "🇩🇰" },
  { iso: "FI", name: "Finland", dial: "358", flag: "🇫🇮" },
  { iso: "IE", name: "Ireland", dial: "353", flag: "🇮🇪" },
  { iso: "BE", name: "Belgium", dial: "32", flag: "🇧🇪" },
  { iso: "CH", name: "Switzerland", dial: "41", flag: "🇨🇭" },
  { iso: "AT", name: "Austria", dial: "43", flag: "🇦🇹" },
  { iso: "PT", name: "Portugal", dial: "351", flag: "🇵🇹" },
  { iso: "PL", name: "Poland", dial: "48", flag: "🇵🇱" },
  { iso: "CZ", name: "Czech Republic", dial: "420", flag: "🇨🇿" },
  { iso: "GR", name: "Greece", dial: "30", flag: "🇬🇷" },
  { iso: "RO", name: "Romania", dial: "40", flag: "🇷🇴" },
  { iso: "HU", name: "Hungary", dial: "36", flag: "🇭🇺" },
  { iso: "TR", name: "Turkey", dial: "90", flag: "🇹🇷" },
  { iso: "RU", name: "Russia", dial: "7", flag: "🇷🇺" },
  { iso: "UA", name: "Ukraine", dial: "380", flag: "🇺🇦" },
  { iso: "IL", name: "Israel", dial: "972", flag: "🇮🇱" },
  { iso: "AE", name: "United Arab Emirates", dial: "971", flag: "🇦🇪" },
  { iso: "SA", name: "Saudi Arabia", dial: "966", flag: "🇸🇦" },
  { iso: "QA", name: "Qatar", dial: "974", flag: "🇶🇦" },
  { iso: "KW", name: "Kuwait", dial: "965", flag: "🇰🇼" },
  { iso: "BH", name: "Bahrain", dial: "973", flag: "🇧🇭" },
  { iso: "OM", name: "Oman", dial: "968", flag: "🇴🇲" },
  { iso: "JO", name: "Jordan", dial: "962", flag: "🇯🇴" },
  { iso: "LB", name: "Lebanon", dial: "961", flag: "🇱🇧" },
  { iso: "EG", name: "Egypt", dial: "20", flag: "🇪🇬" },
  { iso: "MA", name: "Morocco", dial: "212", flag: "🇲🇦" },
  { iso: "ZA", name: "South Africa", dial: "27", flag: "🇿🇦" },
  { iso: "NG", name: "Nigeria", dial: "234", flag: "🇳🇬" },
  { iso: "KE", name: "Kenya", dial: "254", flag: "🇰🇪" },
  { iso: "GH", name: "Ghana", dial: "233", flag: "🇬🇭" },
  { iso: "ET", name: "Ethiopia", dial: "251", flag: "🇪🇹" },
  { iso: "TZ", name: "Tanzania", dial: "255", flag: "🇹🇿" },
  { iso: "UG", name: "Uganda", dial: "256", flag: "🇺🇬" },
  { iso: "PK", name: "Pakistan", dial: "92", flag: "🇵🇰" },
  { iso: "BD", name: "Bangladesh", dial: "880", flag: "🇧🇩" },
  { iso: "LK", name: "Sri Lanka", dial: "94", flag: "🇱🇰" },
  { iso: "NP", name: "Nepal", dial: "977", flag: "🇳🇵" },
  { iso: "ID", name: "Indonesia", dial: "62", flag: "🇮🇩" },
  { iso: "PH", name: "Philippines", dial: "63", flag: "🇵🇭" },
  { iso: "MY", name: "Malaysia", dial: "60", flag: "🇲🇾" },
  { iso: "SG", name: "Singapore", dial: "65", flag: "🇸🇬" },
  { iso: "TH", name: "Thailand", dial: "66", flag: "🇹🇭" },
  { iso: "VN", name: "Vietnam", dial: "84", flag: "🇻🇳" },
  { iso: "KR", name: "South Korea", dial: "82", flag: "🇰🇷" },
  { iso: "TW", name: "Taiwan", dial: "886", flag: "🇹🇼" },
  { iso: "HK", name: "Hong Kong", dial: "852", flag: "🇭🇰" },
  { iso: "NZ", name: "New Zealand", dial: "64", flag: "🇳🇿" },
  { iso: "AR", name: "Argentina", dial: "54", flag: "🇦🇷" },
  { iso: "CL", name: "Chile", dial: "56", flag: "🇨🇱" },
  { iso: "CO", name: "Colombia", dial: "57", flag: "🇨🇴" },
  { iso: "PE", name: "Peru", dial: "51", flag: "🇵🇪" },
  { iso: "VE", name: "Venezuela", dial: "58", flag: "🇻🇪" },
  { iso: "EC", name: "Ecuador", dial: "593", flag: "🇪🇨" },
  { iso: "BO", name: "Bolivia", dial: "591", flag: "🇧🇴" },
  { iso: "PY", name: "Paraguay", dial: "595", flag: "🇵🇾" },
  { iso: "UY", name: "Uruguay", dial: "598", flag: "🇺🇾" },
  { iso: "CR", name: "Costa Rica", dial: "506", flag: "🇨🇷" },
  { iso: "PA", name: "Panama", dial: "507", flag: "🇵🇦" },
  { iso: "GT", name: "Guatemala", dial: "502", flag: "🇬🇹" },
  { iso: "DO", name: "Dominican Republic", dial: "1", flag: "🇩🇴" },
  { iso: "PR", name: "Puerto Rico", dial: "1", flag: "🇵🇷" },
  { iso: "JM", name: "Jamaica", dial: "1", flag: "🇯🇲" },
  { iso: "BS", name: "Bahamas", dial: "1", flag: "🇧🇸" },
  { iso: "TT", name: "Trinidad & Tobago", dial: "1", flag: "🇹🇹" },
  { iso: "BB", name: "Barbados", dial: "1", flag: "🇧🇧" },
  { iso: "IS", name: "Iceland", dial: "354", flag: "🇮🇸" },
  { iso: "LU", name: "Luxembourg", dial: "352", flag: "🇱🇺" },
  { iso: "BG", name: "Bulgaria", dial: "359", flag: "🇧🇬" },
  { iso: "HR", name: "Croatia", dial: "385", flag: "🇭🇷" },
  { iso: "RS", name: "Serbia", dial: "381", flag: "🇷🇸" },
  { iso: "SK", name: "Slovakia", dial: "421", flag: "🇸🇰" },
  { iso: "SI", name: "Slovenia", dial: "386", flag: "🇸🇮" },
  { iso: "EE", name: "Estonia", dial: "372", flag: "🇪🇪" },
  { iso: "LV", name: "Latvia", dial: "371", flag: "🇱🇻" },
  { iso: "LT", name: "Lithuania", dial: "370", flag: "🇱🇹" },
  { iso: "BY", name: "Belarus", dial: "375", flag: "🇧🇾" },
  { iso: "KZ", name: "Kazakhstan", dial: "7", flag: "🇰🇿" },
  { iso: "UZ", name: "Uzbekistan", dial: "998", flag: "🇺🇿" },
  { iso: "AZ", name: "Azerbaijan", dial: "994", flag: "🇦🇿" },
  { iso: "AM", name: "Armenia", dial: "374", flag: "🇦🇲" },
  { iso: "GE", name: "Georgia", dial: "995", flag: "🇬🇪" },
  { iso: "IR", name: "Iran", dial: "98", flag: "🇮🇷" },
  { iso: "IQ", name: "Iraq", dial: "964", flag: "🇮🇶" },
  { iso: "AF", name: "Afghanistan", dial: "93", flag: "🇦🇫" },
  { iso: "MM", name: "Myanmar", dial: "95", flag: "🇲🇲" },
  { iso: "KH", name: "Cambodia", dial: "855", flag: "🇰🇭" },
  { iso: "LA", name: "Laos", dial: "856", flag: "🇱🇦" },
  { iso: "MN", name: "Mongolia", dial: "976", flag: "🇲🇳" },
  { iso: "MO", name: "Macau", dial: "853", flag: "🇲🇴" },
  { iso: "BN", name: "Brunei", dial: "673", flag: "🇧🇳" },
  { iso: "FJ", name: "Fiji", dial: "679", flag: "🇫🇯" },
  { iso: "MT", name: "Malta", dial: "356", flag: "🇲🇹" },
  { iso: "CY", name: "Cyprus", dial: "357", flag: "🇨🇾" },
  { iso: "AL", name: "Albania", dial: "355", flag: "🇦🇱" },
  { iso: "MK", name: "North Macedonia", dial: "389", flag: "🇲🇰" },
  { iso: "BA", name: "Bosnia & Herzegovina", dial: "387", flag: "🇧🇦" },
  { iso: "MD", name: "Moldova", dial: "373", flag: "🇲🇩" },
  { iso: "DZ", name: "Algeria", dial: "213", flag: "🇩🇿" },
  { iso: "TN", name: "Tunisia", dial: "216", flag: "🇹🇳" },
  { iso: "LY", name: "Libya", dial: "218", flag: "🇱🇾" },
  { iso: "SD", name: "Sudan", dial: "249", flag: "🇸🇩" },
  { iso: "AO", name: "Angola", dial: "244", flag: "🇦🇴" },
  { iso: "ZM", name: "Zambia", dial: "260", flag: "🇿🇲" },
  { iso: "ZW", name: "Zimbabwe", dial: "263", flag: "🇿🇼" },
  { iso: "CM", name: "Cameroon", dial: "237", flag: "🇨🇲" },
  { iso: "CI", name: "Côte d'Ivoire", dial: "225", flag: "🇨🇮" },
  { iso: "SN", name: "Senegal", dial: "221", flag: "🇸🇳" },
  { iso: "RW", name: "Rwanda", dial: "250", flag: "🇷🇼" },
];

export const DEFAULT_COUNTRY: Country = COUNTRIES.find((c) => c.iso === "US") ?? COUNTRIES[0];

export function findByIso(iso: string): Country | undefined {
  return COUNTRIES.find((c) => c.iso === iso);
}

export function bestMatchByDial(dial: string): Country | undefined {
  return COUNTRIES.find((c) => c.dial === dial);
}
